## What is an array?

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst) #creates an array 

In [3]:
type(arr)

numpy.ndarray

In [5]:
arr #1D array

array([1, 2, 3, 4, 5])

In [6]:
arr.shape #returns array dimensions (rows and column for 2D)

(5,)

In [7]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3]) #converting list to array

In [8]:
arr #2D as two opening brackets and two closing brackets

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
arr.shape #rows and column

(3, 5)

In [10]:
arr.reshape(5,3) #same no. of elements but with different rows and columns

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

## Indexing

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9]) #creating an array

In [14]:
arr[3] #accessing 1D array

4

In [19]:
#2D array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [20]:
arr[:,:] #executing all the rows and columns :

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
arr[0:2,:] #only first two rows and all their column

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [22]:
arr[0:2,0:2] #only first two rows and first two columns

array([[1, 2],
       [2, 3]])

In [25]:
#pick 5,6,8,9
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [29]:
#pick 4,5,6,8
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [31]:
#pick up 3,4,5 
arr[1:2,1:4]

array([[3, 4, 5]])

In [34]:
arr=np.arange(0,10) #create an array of evenly spaced values within a specified range
arr                 #0 (inclusive) up to 10 (exclusive)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr=np.arange(0,10,step=2) #step size between consecutive values in the array.
arr

array([0, 2, 4, 6, 8])

In [38]:
np.linspace(0,10,5) #generates an array of 5 evenly spaced values between 0 and 10.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Unlike np.arange(), which generates values with a constant step size, np.linspace() generates values with a specified number of points between the start and end points, resulting in a consistent spacing between the values

In [ ]:
#copy function