## What is an array?

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst) #creates an array 

In [3]:
type(arr)

numpy.ndarray

In [5]:
arr #1D array

array([1, 2, 3, 4, 5])

In [6]:
arr.shape #returns array dimensions (rows and column for 2D)

(5,)

In [7]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3]) #converting list to array

In [8]:
arr #2D as two opening brackets and two closing brackets

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
arr.shape #rows and column

(3, 5)

In [10]:
arr.reshape(5,3) #same no. of elements but with different rows and columns

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

## Indexing

In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9]) #creating an array

In [14]:
arr[3] #accessing 1D array

4

In [19]:
#2D array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [20]:
arr[:,:] #executing all the rows and columns :

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [21]:
arr[0:2,:] #only first two rows and all their column

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [22]:
arr[0:2,0:2] #only first two rows and first two columns

array([[1, 2],
       [2, 3]])

In [25]:
#pick 5,6,8,9
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [29]:
#pick 4,5,6,8
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [31]:
#pick up 3,4,5 
arr[1:2,1:4]

array([[3, 4, 5]])

In [34]:
arr=np.arange(0,10) #create an array of evenly spaced values within a specified range
arr                 #0 (inclusive) up to 10 (exclusive)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr=np.arange(0,10,step=2) #step size between consecutive values in the array.
arr

array([0, 2, 4, 6, 8])

In [38]:
np.linspace(0,10,5) #generates an array of 5 evenly spaced values between 0 and 10.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Unlike np.arange(), which generates values with a constant step size, np.linspace() generates values with a specified number of points between the start and end points, resulting in a consistent spacing between the values

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [8]:
#copy function and broadcasting
arr[3:]=100 #from 3rd index replace all by 100
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [9]:
arr1=arr #assigning arr to arr1

In [10]:
arr1[3:]=500 #replacing with 500 
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [11]:
arr #changing arr1 has changed arr too (reference type = sharing the same memory)

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [12]:
#to prevent reference type, we have copy function 
arr1=arr.copy()

In [13]:
print(arr)
arr1[3:]=1000 #replace it by 1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [14]:
arr #checking the previous array and it didn't change

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [15]:
#conditions in exploratory data analysis
val = 2
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [16]:
arr*2 #multiplication of arrays

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [17]:
arr/2 #division of arrays

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. , 250. ])

In [19]:
arr[arr<2] #to find the specific element less than 2

array([1])

In [20]:
np.ones(4) #creates 4 ones in array

array([1., 1., 1., 1.])

In [21]:
np.ones((2,5),dtype=int) #2D array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
 #random distribution
np.random.rand(3,3) #gives random value from 0 to 1 

array([[0.35182275, 0.46745773, 0.91585381],
       [0.0807821 , 0.25815438, 0.18973698],
       [0.05611129, 0.25992319, 0.37128882]])

In [23]:
arr2=np.random.randn(4,4) #sample from standard normal distribution
arr2

array([[-3.99337844e-01, -1.33546496e+00,  6.31835272e-01,
         1.37953238e+00],
       [-9.72060124e-01, -1.27470726e+00, -1.28486130e+00,
         7.97965272e-01],
       [-1.80087743e-01, -1.10145727e+00, -1.26655482e-03,
         1.50377901e-01],
       [ 3.63126701e-01, -7.47942367e-02, -5.46076245e-01,
         4.76664051e-01]])

In [3]:
#randint provides with integer
np.random.randint(0,100,8) #b/w 0 to 100 select 8 numbers

array([40, 91, 39, 58, 57, 20, 64, 21])